FROM public.ecr.aws/docker/library/python:3.11.6-slim-bullseye
ENV NX_API_URL_RESOURCE=https://3s0j75sb7l.execute-api.eu-west-2.amazonaws.com/dev/resource/api/resource
ENV NX_API_URL_ACTIVITY=https://fi0rey2ut2.execute-api.eu-west-2.amazonaws.com/dev/activity/api
ENV NX_API_URL_ASSESSMENT=https://26hcag1zwc.execute-api.eu-west-2.amazonaws.com/dev/assessment/api/assessment
ENV SOLVER_MAX_MINUTES=10
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
CMD python main.py